version: '3.9'

services:
  db:
    image: postgres:17.0-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./be/.postgres-data:/var/lib/postgresql/data
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:2024-10-15-1
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./be/.pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres

  be:
    image: asanand1996/be
    container_name: be
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      PORT: 8001

  fe:
    image: asanand1996/fe
    container_name: fe
    restart: always
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      API_PORT: 8001
