version: '3.9'

services:
  db:
    image: postgres:17.0-alpine
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: mgmt-sys
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:2024-10-15-1
    restart: always
    ports:
      - ${PG_ADMIN_PORT}:80
    volumes:
      - ${PGADMIN_VOLUME}:/var/lib/pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  be:
    image: asanand1996/be
    container_name: be
    restart: always
    ports:
      - ${API_PORT}:8001
    environment:
      PORT: ${API_PORT}
      DB_PORT: ${DB_PORT}
      DB_HOSTNAME: ${DB_HOSTNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  fe:
    image: asanand1996/fe
    container_name: fe
    restart: always
    ports:
      - ${CLIENT_PORT}:8000
    environment:
      PORT: ${CLIENT_PORT}
      API_PORT: ${API_PORT}
