# Fetching the minified node image on apline linux
FROM node:22.9.0-alpine

# Setting up the work directory
WORKDIR /fe

# Copying all the files in our project
COPY . /

# Installing dependencies
RUN npm install

ARG REACT_APP_PORT
ENV REACT_APP_PORT $REACT_APP_PORT

ARG REACT_APP_GOOGLE_CLIENT_ID
ENV REACT_APP_GOOGLE_CLIENT_ID $REACT_APP_GOOGLE_CLIENT_ID

ARG REACT_APP_GOOGLE_API_KEY
ENV REACT_APP_GOOGLE_API_KEY $REACT_APP_GOOGLE_API_KEY

RUN npm run build

# Starting our application
CMD [ "npm", "run", "docker-start" ]