# Fetching the minified node image on apline linux
FROM node:22.9.0-slim

# Declaring env
ENV API_PORT=8000

# Setting up the work directory
WORKDIR /be

# Copying all the files in our project
COPY . .

# Exposing server port
EXPOSE 8000

# Installing dependencies
RUN npm install

# Starting our application
CMD [ "node", "./bin/www" ]