# Fetching the minified node image on apline linux
FROM node:22.9.0-slim

# Setting up the work directory
WORKDIR /be

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

# Starting our application
CMD [ "node", "./bin/www" ]