# Fetching the minified node image on apline linux
FROM node:22.9.0-slim as build

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

RUN npm run build

# Starting our application
CMD [ "npm", "run", "server" ]